parent=keycloak.v2

# Override title and description
title=V-App Administration Console
description=The V-App Administration Console is a web-based interface for managing your V-App platform.

# Custom styles
styles=css/v-app-admin.css

# Dark mode
darkMode=true
kcDarkModeClass=pf-v5-theme-dark

# Override favicon (use same as login)
# favIcon=/favicon.svg
contentHashPattern=assets/.*
