parent=keycloak.v3

# Override title and description
title=V-App Account Management
description=The V-App Account Console is a web-based interface for managing your account.

# Custom styles
styles=css/v-app-account.css

# Dark mode
deprecatedMode=false
darkMode=true
kcDarkModeClass=pf-v5-theme-dark

favIcon=/favicon.svg
favIconType=image/svg+xml
logo=/logo.svg
logoUrl=/logo.svg

contentHashPattern=assets/.*
