# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=mysql

# The username of the database user.
db-username=root
# db-username=avnadmin

# The password of the database user.
db-password=SIva@7482
# db-password=AVNS_8_YjDdjbxc4X4KJahZt

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:mysql://100.122.105.63:3306/keycloak?allowPublicKeyRetrieval=true&useSSL=false
# db-url=jdbc:mysql://mysql-21e13220-v-app.j.aivencloud.com:20632/keycloak?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&sessionVariables=sql_require_primary_key=0

# Hostname (for development)
# hostname=localhost
# hostname=mysql-21e13220-v-app.j.aivencloud.com
hostname-strict=false
http-enabled=true

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}/conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}/conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
#hostname=myhostname
