<#import "template.ftl" as layout>
<#import "password-commons.ftl" as passwordCommons>
<@layout.registrationLayout displayRequiredFields=false displayMessage=!messagesPerField.existsError('totp','userLabel'); section>

    <#if section = "header">
        ${msg("loginTotpTitle")}
    <#elseif section = "form">
        <div class="vf-totp-enclave-grid">
            <!-- LEFT COLUMN: QR Code & Setup Instructions -->
            <div class="vf-totp-col-qr">
                <div class="vf-totp-step-badge">1. Scan Barcode</div>
                <p class="vf-totp-hint">Open your authenticator app (Google Authenticator, Microsoft Authenticator, FreeOTP) and scan the QR barcode:</p>

                <#if mode?? && mode = "manual">
                    <div class="vf-totp-manual-box">
                        <span class="vf-totp-manual-label">Secret Key:</span>
                        <code id="kc-totp-secret-key">${totp.totpSecretEncoded}</code>
                    </div>
                    <p><a href="${totp.qrUrl}" id="mode-barcode" class="vf-totp-link">${msg("loginTotpScanBarcode")}</a></p>
                <#else>
                    <div class="vf-totp-qr-wrapper">
                        <img id="kc-totp-secret-qr-code" src="data:image/png;base64, ${totp.totpSecretQrCode}" alt="Figure: Barcode">
                    </div>
                    <p><a href="${totp.manualUrl}" id="mode-manual" class="vf-totp-link">${msg("loginTotpUnableToScan")}</a></p>
                </#if>
            </div>

            <!-- RIGHT COLUMN: Verification Code & Submit Actions -->
            <div class="vf-totp-col-verify">
                <div class="vf-totp-step-badge">2. Verify & Register</div>
                <p class="vf-totp-hint">Enter the 6-digit one-time code generated by your app to register this device.</p>

                <form action="${url.loginAction}" class="${properties.kcFormClass!}" id="kc-totp-settings-form" method="post">
                    <div class="form-group" style="margin-bottom: 12px;">
                        <label for="totp" class="pf-c-form__label pf-c-form__label-text">${msg("authenticatorCode")} *</label>
                        <div class="vf-input-box">
                            <input type="text" id="totp" name="totp" autocomplete="one-time-code" class="pf-c-form-control vf-capsule-input"
                                   placeholder="000 000"
                                   maxlength="8"
                                   aria-invalid="<#if messagesPerField.existsError('totp')>true</#if>"
                                   inputmode="numeric"
                                   dir="ltr"
                                   autofocus
                            />
                        </div>
                        <#if messagesPerField.existsError('totp')>
                            <span id="input-error-otp-code" class="vf-input-error" aria-live="polite">
                                ${kcSanitize(messagesPerField.get('totp'))?no_esc}
                            </span>
                        </#if>
                    </div>

                    <div class="form-group" style="margin-bottom: 12px;">
                        <label for="userLabel" class="pf-c-form__label pf-c-form__label-text">${msg("loginTotpDeviceName")}</label>
                        <div class="vf-input-box">
                            <input type="text" class="pf-c-form-control vf-capsule-input" id="userLabel" name="userLabel" autocomplete="off"
                                   placeholder="e.g. My Phone"
                                   aria-invalid="<#if messagesPerField.existsError('userLabel')>true</#if>" dir="ltr"
                            />
                        </div>
                        <#if messagesPerField.existsError('userLabel')>
                            <span id="input-error-otp-label" class="vf-input-error" aria-live="polite">
                                ${kcSanitize(messagesPerField.get('userLabel'))?no_esc}
                            </span>
                        </#if>
                    </div>

                    <div class="form-group vf-totp-signout-row" style="margin-bottom: 16px;">
                        <@passwordCommons.logoutOtherSessions/>
                    </div>

                    <input type="hidden" id="totpSecret" name="totpSecret" value="${totp.totpSecret}" />
                    <#if mode??><input type="hidden" id="mode" name="mode" value="${mode}"/></#if>

                    <div class="vf-totp-actions">
                        <input type="submit"
                               class="pf-c-button pf-m-primary vf-capsule-btn"
                               id="saveTOTPBtn" value="${msg("doSubmit")}"
                        />
                        <#if isAppInitiatedAction??>
                            <button type="submit"
                                    class="pf-c-button pf-m-secondary vf-capsule-btn vf-btn-ghost"
                                    id="cancelTOTPBtn" name="cancel-aia" value="true">${msg("doCancel")}
                            </button>
                        </#if>
                    </div>
                </form>
            </div>
        </div>
    </#if>
</@layout.registrationLayout>
