parent=keycloak
import=common/keycloak

# Custom properties
styles=css/volt.css
scripts=js/volt-canvas.js js/volt.js

# Override Keycloak logo link
kcLogoLink=#

# Custom Favicon
favIcon=/img/favicon.svg
favIconType=image/svg+xml

meta=viewport==width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no

# Theme classes
kcHtmlClass=login-pf volt-theme
kcLoginClass=login-pf-page
kcHeaderClass=login-pf-page-header
kcFormCardClass=card-pf
kcFormHeaderClass=login-pf-header
kcFormGroupClass=form-group
kcFormClass=
kcLabelWrapperClass=
kcInputWrapperClass=
kcFormOptionsClass=
kcFormButtonsClass=
kcInputClass=pf-c-form-control
kcButtonClass=pf-c-button
kcButtonPrimaryClass=pf-m-primary
kcFeedbackErrorIcon=fa fa-fw fa-exclamation-circle

# Branding
kcLogoClass=login-pf-brand
