import=common/keycloak

stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css
styles=css/welcome.css css/v-app-welcome.css

# When set to true, the user will be redirected to the Administration Console if an administrative user already exists.
redirectToAdmin=true
darkMode=true

kcDarkModeClass=pf-v5-theme-dark

# Custom Favicon
favIcon=/img/favicon.svg
favIconType=image/svg+xml
