parent=keycloak
import=common/keycloak

# Custom properties
styles=css/v-app.css
scripts=js/v-app.js

# Override Keycloak logo link
kcLogoLink=#

meta=viewport==width=device-width,initial-scale=1

# Theme classes
kcHtmlClass=login-pf
kcLoginClass=login-pf-page
kcHeaderClass=login-pf-page-header
kcFormCardClass=card-pf
kcFormHeaderClass=login-pf-header
kcFormGroupClass=form-group
kcInputClass=pf-c-form-control
kcButtonClass=pf-c-button
kcButtonPrimaryClass=pf-m-primary
kcFeedbackErrorIcon=fa fa-fw fa-exclamation-circle

# Branding
kcLogoClass=login-pf-brand
